### ISSUE TITLE
Does internet speed matter?

### ISSUE THREAD

**Issue by HarshRangwala** [SochInc/Self-Driving-RC-Car#14]
I have followed all the necessary steps and my car operates fine during testing phase. but as soon as I connect via server nothing happens. I dont get the pygame window. It worked once or twice earlier during training phase but it isnt working now.  
Could the wifi speed matters? why is it delaying so much?

please let me know.

**Comment by l3lackcurtains** [comment]
Wifi speed doesn't matter. I hope you are running in a local network.

There might be a chance that your motor is not quickly switching on and off (happens to synchronize with your keyboard press).

**Comment by HarshRangwala** [comment]
But it works properly sometimes. Now everytime i run a in a given sequence, the pygame window unfortunately stops. I get this message:
```
HTTPConnectionPool(host='192.168.0.28', port=5000): Max retries exceeded with url: /messages?
data=s (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x000002B7F5943A08>: Failed to establish a new connection: [WinError 10060] A connection 
attempt failed because the connected party did not properly respond after a period of time, or 
established connection failed because connected host has failed to respond'))

```

**Comment by l3lackcurtains** [comment]
It seems certain that it is a problem associated with the network requests being refused because of many requests.

**Possible solutions:**
- Try using a different port
- After sending a request, sleep for some seconds or milliseconds. Do this to put some delay in a request.
- Try using different HTTP library

The problem is with urllib3 library. Check the documentation and github for issues.
